import React from "react";
import { BookOpen, Camera, Database, PackageSearch, Save, Wrench, Zap } from "lucide-react";
import { Badge } from "../CheckItem";
import { diagnosisOrderStatuses } from "../../lib/diagnosisAssistant";

function ResultList({ empty, items = [], title }) {
  return <div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-black uppercase text-slate-500">{title}</p><div className="mt-3 space-y-2">{items.length ? items.map((item) => <div key={item} className="rounded-xl bg-white p-3 text-xs font-bold leading-5">{item}</div>) : <p className="text-xs font-semibold text-slate-400">{empty}</p>}</div></div>;
}

export default function DiagnosisResult({ onCreatePartRequest, onOpenKnowledge, onOpenLearning, onOpenManufacturer, onOpenMotors, onOpenParts, onPhoto, onSaveLearningCase, onSaveLocal, onSaveOrder, onStatusChange, result, session, tree }) {
  return <section className="space-y-4 rounded-3xl border border-emerald-200 bg-emerald-50/50 p-4 md:p-6">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2"><Badge>Ergebnis</Badge><Badge>{result.safetyLevel}</Badge></div><h2 className="mt-3 text-xl font-black">Wahrscheinlicher Bereich: {result.probableCause}</h2><p className="mt-2 max-w-3xl text-xs font-semibold leading-5 text-slate-600">{result.uncertainty}</p></div><label className="text-xs font-black uppercase text-slate-500">Auftragsstatus<select value={session.orderStatus || result.orderStatus} onChange={(event) => onStatusChange(event.target.value)} className="mt-2 block min-h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm font-black normal-case text-slate-900">{diagnosisOrderStatuses.map((status) => <option key={status}>{status}</option>)}</select></label></div>
    <div className="grid gap-3 lg:grid-cols-3"><ResultList title="Mögliche Ursachen" items={result.possibleCauses} empty="Noch offen" /><ResultList title="Geprüft" items={result.checkedSteps} empty="Noch kein Punkt bestätigt" /><ResultList title="Noch offen" items={result.openSteps} empty="Alle vorgesehenen Schritte beantwortet" /></div>
    <div className="rounded-2xl bg-white p-4"><p className="text-xs font-black uppercase text-slate-500">Empfohlene nächste Aktion</p><p className="mt-2 text-sm font-bold leading-6">{result.recommendation}</p></div>
    <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5"><button type="button" onClick={onSaveLocal} className="flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-slate-950 px-3 text-xs font-black text-white"><Save size={16} />Lokal speichern</button>{session.context.orderId && <button type="button" onClick={onSaveOrder} className="min-h-12 rounded-2xl bg-emerald-600 px-3 text-xs font-black text-white">Zum Auftrag speichern</button>}<button type="button" onClick={onPhoto} className="flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-white px-3 text-xs font-black"><Camera size={16} />Foto ergänzen</button><button type="button" onClick={() => onCreatePartRequest(tree, session)} className="flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-white px-3 text-xs font-black"><PackageSearch size={16} />Ersatzteil-Anfrage</button>{onSaveLearningCase && <button type="button" onClick={onSaveLearningCase} className="flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-white px-3 text-xs font-black"><BookOpen size={16} />Als Lernfall speichern</button>}</div>
    <details className="rounded-2xl bg-white p-4"><summary className="cursor-pointer text-xs font-black uppercase text-slate-500">Verknüpfte Fachbereiche</summary><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-5"><button type="button" onClick={() => onOpenParts(tree)} className="min-h-11 rounded-xl bg-slate-100 px-3 text-xs font-black"><PackageSearch size={15} className="mr-1 inline" />Ersatzteile</button><button type="button" onClick={() => onOpenManufacturer(tree)} className="min-h-11 rounded-xl bg-slate-100 px-3 text-xs font-black"><Database size={15} className="mr-1 inline" />Hersteller</button><button type="button" onClick={() => onOpenMotors(session, tree)} className="min-h-11 rounded-xl bg-slate-100 px-3 text-xs font-black"><Zap size={15} className="mr-1 inline" />Motor-Assistent</button><button type="button" onClick={() => onOpenLearning(tree)} className="min-h-11 rounded-xl bg-slate-100 px-3 text-xs font-black"><BookOpen size={15} className="mr-1 inline" />Mehr lernen</button><button type="button" onClick={() => onOpenKnowledge(tree)} className="min-h-11 rounded-xl bg-slate-100 px-3 text-xs font-black"><Wrench size={15} className="mr-1 inline" />Wissen öffnen</button></div></details>
  </section>;
}
