import React, { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, ClipboardCopy, Eye, FileText, Pencil, Printer, RefreshCw, Save } from "lucide-react";
import { Field, TextArea } from "../Field";
import SignaturePad from "./SignaturePad";
import DocumentPreview from "./DocumentPreview";

const completenessStyles = {
  green: "bg-emerald-50 text-emerald-900",
  yellow: "bg-amber-50 text-amber-900",
  red: "bg-rose-50 text-rose-900",
};

function EditorField({ field, onChange, value }) {
  const requiredLabel = field.required ? "Pflicht" : field.recommended ? "empfohlen" : "";
  if (field.type === "checkbox") return <button type="button" id={`document-field-${field.key}`} onClick={() => onChange(!value)} className={`flex min-h-12 w-full items-start gap-3 rounded-2xl border p-3 text-left text-sm font-bold ${value ? "border-emerald-200 bg-emerald-50 text-emerald-900" : field.required ? "border-rose-200 bg-rose-50 text-rose-900" : "border-slate-200 bg-white text-slate-700"}`}><span className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded border ${value ? "border-emerald-700 bg-emerald-700 text-white" : "border-slate-300"}`}>{value ? "✓" : ""}</span><span>{field.label}{requiredLabel && <small className="ml-2 text-[10px] uppercase opacity-60">{requiredLabel}</small>}</span></button>;
  if (field.type === "textarea") return <div id={`document-field-${field.key}`}><TextArea label={`${field.label}${requiredLabel ? ` · ${requiredLabel}` : ""}`} value={value || ""} onChange={onChange} placeholder={field.placeholder || ""} /></div>;
  if (field.type === "select") return <label id={`document-field-${field.key}`} className="block rounded-2xl bg-slate-50 p-4 text-sm font-bold">{field.label}{requiredLabel && <span className="ml-2 text-[10px] uppercase text-slate-400">{requiredLabel}</span>}<select value={value || ""} onChange={(event) => onChange(event.target.value)} className="mt-2 min-h-12 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">Bitte auswählen</option>{field.options.map((option) => <option key={option}>{option}</option>)}</select></label>;
  return <div id={`document-field-${field.key}`}><Field label={`${field.label}${requiredLabel ? ` · ${requiredLabel}` : ""}`} type={field.type || "text"} value={value || ""} onChange={onChange} placeholder={field.placeholder || ""} /></div>;
}

export default function DocumentEditor({ company, completeness, customerVersion, document, fields, fileName, onCopy, onCustomerVersionChange, onFieldChange, onPrint, onReset, onSave, onSignatureChange, order, orderPhotos = {}, productName, readOnly = false, savedSketches = [], signatures, template }) {
  const [mobileTab, setMobileTab] = useState("edit");
  const groups = useMemo(() => template.fields.reduce((result, field) => {
    const section = field.section || "Dokument";
    if (!result[section]) result[section] = [];
    result[section].push(field);
    return result;
  }, {}), [template]);
  const availablePhotos = Object.entries(orderPhotos).filter(([, photo]) => photo?.url);
  const orderSketches = savedSketches.filter((sketch) => sketch.orderId === order?.id);
  const selectedPhotos = Array.isArray(fields._photoRefs) ? fields._photoRefs : [];

  const togglePhoto = (category) => onFieldChange("_photoRefs", selectedPhotos.includes(category) ? selectedPhotos.filter((item) => item !== category) : [...selectedPhotos, category]);
  const jumpToMissing = (field) => globalThis.document?.getElementById(`document-field-${field.key}`)?.scrollIntoView({ behavior: "smooth", block: "center" });

  return <div className="space-y-4">
    <div className="no-print flex rounded-2xl bg-slate-100 p-1 lg:hidden"><button type="button" onClick={() => setMobileTab("edit")} className={`flex min-h-11 flex-1 items-center justify-center gap-2 rounded-xl text-sm font-black ${mobileTab === "edit" ? "bg-white shadow-sm" : "text-slate-500"}`}><Pencil size={16} />Bearbeiten</button><button type="button" onClick={() => setMobileTab("preview")} className={`flex min-h-11 flex-1 items-center justify-center gap-2 rounded-xl text-sm font-black ${mobileTab === "preview" ? "bg-white shadow-sm" : "text-slate-500"}`}><Eye size={16} />Vorschau</button></div>
    <div className="grid min-w-0 gap-5 lg:grid-cols-[minmax(360px,0.82fr)_minmax(0,1.18fr)]">
      <section className={`no-print min-w-0 space-y-4 ${mobileTab === "preview" ? "hidden lg:block" : "block"}`}>
        <div className={`rounded-3xl p-4 ${completenessStyles[completeness.level]}`}><div className="flex items-start gap-3">{completeness.level === "green" ? <CheckCircle2 className="shrink-0" /> : <AlertTriangle className="shrink-0" />}<div><h2 className="font-black">{completeness.level === "green" ? "Dokument vollständig" : completeness.level === "yellow" ? "Empfohlene Angaben fehlen" : `${completeness.requiredMissing.length} wichtige Angabe${completeness.requiredMissing.length === 1 ? " fehlt" : "n fehlen"}`}</h2><p className="mt-1 text-xs font-semibold">Der PDF-Druck bleibt möglich; fehlende Angaben werden vorher transparent angezeigt.</p></div></div>{completeness.requiredMissing.length > 0 && <div className="mt-3 flex flex-wrap gap-2">{completeness.requiredMissing.map((field) => <button key={field.key} type="button" onClick={() => jumpToMissing(field)} className="rounded-full bg-white px-3 py-1.5 text-xs font-black">{field.label}</button>)}</div>}</div>
        <div className="rounded-3xl bg-slate-950 p-4 text-white"><p className="text-xs font-black uppercase text-white/50">Aktives Dokument</p><h2 className="mt-1 text-lg font-black">{document.title || template.title}</h2><p className="mt-1 text-xs font-semibold text-white/60">{document.documentNumber || "Neue Vorlage"} · Version {document.version || 1}</p><p className="mt-3 break-all rounded-xl bg-white/10 p-3 text-xs font-bold">{fileName}</p></div>
        {Object.entries(groups).map(([section, sectionFields]) => <details key={section} open className="rounded-3xl border border-slate-200 bg-white"><summary className="cursor-pointer list-none px-4 py-4 font-black">{section}</summary><fieldset disabled={readOnly} className="grid gap-3 border-t border-slate-100 p-4 sm:grid-cols-2">{sectionFields.map((field) => <div key={field.key} className={field.type === "textarea" ? "sm:col-span-2" : ""}><EditorField field={field} value={fields[field.key]} onChange={(value) => onFieldChange(field.key, value)} /></div>)}</fieldset></details>)}
        {(availablePhotos.length > 0 || orderSketches.length > 0) && <details className="rounded-3xl border border-slate-200 bg-white"><summary className="cursor-pointer list-none px-4 py-4 font-black">Fotos & Skizze auswählen</summary><fieldset disabled={readOnly} className="border-t border-slate-100 p-4"><p className="text-xs font-bold uppercase text-slate-400">Nur bewusst ausgewählte Auftragsbilder erscheinen</p><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{availablePhotos.map(([category, photo]) => <button key={category} type="button" onClick={() => togglePhoto(category)} className={`overflow-hidden rounded-2xl border text-left ${selectedPhotos.includes(category) ? "border-slate-950 ring-2 ring-slate-950" : "border-slate-200"}`}><img src={photo.url} alt={category} className="h-24 w-full object-cover" /><span className="block p-2 text-xs font-black">{category}</span></button>)}</div>{orderSketches.length > 0 && <label className="mt-4 block text-sm font-bold">Auftragsskizze<select value={fields._sketchId || ""} onChange={(event) => onFieldChange("_sketchId", event.target.value)} className="mt-2 min-h-12 w-full rounded-xl border border-slate-200 bg-white px-3"><option value="">Keine Skizze einbinden</option>{orderSketches.map((sketch) => <option key={sketch.id} value={sketch.id}>{sketch.title || sketch.useCase}</option>)}</select></label>}</fieldset></details>}
        {!readOnly && template.signatures?.map((label) => <SignaturePad key={label} label={label} value={signatures[label] || {}} onChange={(value) => onSignatureChange(label, value)} />)}
        <label className="flex items-center justify-between gap-3 rounded-2xl bg-slate-50 p-4 text-sm font-black"><span>Kundenversion anzeigen<small className="mt-1 block font-semibold text-slate-500">Interne Felder werden in dieser Ansicht ausgeblendet.</small></span><input type="checkbox" checked={customerVersion} onChange={(event) => onCustomerVersionChange(event.target.checked)} className="h-5 w-5 accent-slate-950" /></label>
        <div className="grid gap-2 sm:grid-cols-2">{!readOnly && <><button type="button" onClick={() => onSave("Entwurf")} className="flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-slate-100 px-4 text-sm font-black"><Save size={17} />Als Entwurf speichern</button><button type="button" onClick={() => onSave("Erstellt")} className="flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-emerald-100 px-4 text-sm font-black text-emerald-950"><FileText size={17} />Dokument erstellen</button></>}<button type="button" onClick={onCopy} className="flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-slate-100 px-4 text-sm font-black"><ClipboardCopy size={17} />Text kopieren</button>{!readOnly && <button type="button" onClick={onReset} className="flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-slate-100 px-4 text-sm font-black"><RefreshCw size={17} />Vorlage zurücksetzen</button>}<button type="button" onClick={onPrint} className="flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-slate-950 px-4 text-sm font-black text-white sm:col-span-2"><Printer size={18} />Nur Vorschau als PDF</button></div>
      </section>
      <section className={`print-area min-w-0 ${mobileTab === "edit" ? "hidden lg:block" : "block"}`}><DocumentPreview company={company} customerVersion={customerVersion} document={document} fields={fields} order={order} productName={productName} signatures={signatures} template={template} />{(selectedPhotos.length > 0 || fields._sketchId) && <div className="print-document mx-auto w-full max-w-[210mm] bg-white px-6 pb-8 sm:px-9"><section className="document-block mt-6"><h3 className="border-b border-slate-300 pb-2 text-sm font-black uppercase tracking-wide">Ausgewählte Dokumentation</h3><div className="mt-3 grid grid-cols-2 gap-3">{selectedPhotos.map((category) => { const photo = orderPhotos[category]; return photo?.url ? <figure key={category} className="document-block"><img src={photo.url} alt={category} className="h-40 w-full rounded-xl border border-slate-200 object-cover" /><figcaption className="mt-1 text-xs font-black">{category}</figcaption></figure> : null; })}{fields._sketchId && (() => { const sketch = savedSketches.find((item) => item.id === fields._sketchId); return sketch ? <figure className="document-block col-span-2"><img src={sketch.image} alt={sketch.title || "Auftragsskizze"} className="max-h-72 w-full rounded-xl border border-slate-200 object-contain" /><figcaption className="mt-1 text-xs font-black">{sketch.title || sketch.useCase || "Auftragsskizze"}</figcaption></figure> : null; })()}</div></section></div>}</section>
    </div>
  </div>;
}
