import React, { useEffect, useState } from "react";
import { CalendarClock, MessageSquareText, RefreshCw, ShieldCheck, TriangleAlert } from "lucide-react";
import Card from "../Card";
import { Badge } from "../CheckItem";
import SectionTitle from "../SectionHeader";
import { getCustomerPortalState } from "../../lib/customerPortal";

export default function OrderCustomerActivity({ canManage, onCreateRework, onNavigatePlanning, onUpdateEntry, order }) {
  const portal = getCustomerPortalState(order);
  const [replyDrafts, setReplyDrafts] = useState({});
  useEffect(() => setReplyDrafts(Object.fromEntries(portal.messages.map((message) => [message.id, message.reply || ""]))), [order.id]);
  const empty = !portal.appointmentRequests.length && !portal.messages.length && !portal.issues.length && !portal.maintenanceRequests.length && !portal.approvals.length && !portal.feedback.length;
  return <div className="space-y-4"><Card><SectionTitle icon={MessageSquareText} title="Kundenaktivität" subtitle="Terminwünsche, Rückfragen, Meldungen und Freigaben aus dem Kundenportal." />{empty && <p className="rounded-2xl bg-slate-50 p-4 text-sm font-bold text-slate-500">Noch keine Kundenaktivität zu diesem Auftrag.</p>}
    <div className="space-y-3">{portal.appointmentRequests.map((request) => <article key={request.id} className="rounded-3xl bg-sky-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="flex items-center gap-2 font-black"><CalendarClock size={18} />Terminänderung</p><Badge>{request.status}</Badge></div><p className="mt-2 text-sm">Wunsch: {request.preferredDate || "ohne konkretes Datum"} · {request.timeWindow || "egal"}</p>{request.message && <p className="mt-2 rounded-2xl bg-white p-3 text-sm">{request.message}</p>}{canManage && ["Anfrage gesendet", "wird geprüft"].includes(request.status) && <div className="mt-3 grid gap-2 sm:grid-cols-2"><button type="button" onClick={() => onUpdateEntry("appointmentRequests", request.id, { status: "wird geprüft" })} className="min-h-11 rounded-xl bg-white px-3 text-xs font-black">Als geprüft markieren</button><button type="button" onClick={onNavigatePlanning} className="min-h-11 rounded-xl bg-sky-950 px-3 text-xs font-black text-white">In Planung öffnen</button></div>}</article>)}
    {portal.messages.map((message) => <article key={message.id} className="rounded-3xl bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-black">Rückfrage · {message.topic}</p><Badge>{message.status}</Badge></div><p className="mt-2 text-sm">{message.message}</p>{canManage && <><label className="mt-3 block text-xs font-black">Antwort<textarea value={replyDrafts[message.id] ?? message.reply ?? ""} onChange={(event) => setReplyDrafts((current) => ({ ...current, [message.id]: event.target.value }))} className="mt-1 h-20 w-full resize-none rounded-xl border border-slate-200 bg-white p-3 text-sm font-medium" /></label><button type="button" onClick={() => onUpdateEntry("messages", message.id, { reply: replyDrafts[message.id] || "", status: (replyDrafts[message.id] || "").trim() ? "beantwortet" : "gelesen" })} className="mt-2 min-h-11 w-full rounded-xl bg-slate-950 px-3 text-xs font-black text-white">Antwort speichern</button></>}</article>)}
    {portal.issues.map((issue) => <article key={issue.id} className="rounded-3xl bg-amber-50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="flex items-center gap-2 font-black"><TriangleAlert size={18} />Kundenmeldung · {issue.category}</p><Badge>{issue.status}</Badge></div><p className="mt-2 text-sm">{issue.description}</p><p className="mt-1 text-xs font-bold text-amber-900">Anlage nutzbar: {issue.usable || "nicht angegeben"}</p>{issue.photo?.dataUrl && <img src={issue.photo.dataUrl} alt="Foto zur Kundenmeldung" className="mt-3 max-h-56 w-full rounded-2xl object-cover" />}{canManage && <label className="mt-3 block text-xs font-black">Bearbeitungsstatus<select value={issue.status || "gemeldet"} onChange={(event) => onUpdateEntry("issues", issue.id, { status: event.target.value })} className="mt-1 min-h-11 w-full rounded-xl border border-amber-200 bg-white px-3 text-sm"><option>gemeldet</option><option>wird geprüft</option><option>Termin wird geplant</option><option>Nacharbeit geplant</option><option>erledigt</option></select></label>}{canManage && !issue.reworkOrderId && <button type="button" onClick={() => onCreateRework(issue)} className="mt-3 min-h-11 w-full rounded-xl bg-amber-950 px-3 text-xs font-black text-white">Nacharbeit vorbereiten</button>}{issue.reworkOrderId && <p className="mt-3 rounded-xl bg-white p-3 text-sm font-black">Nacharbeit: {issue.reworkOrderId}</p>}</article>)}
    {portal.maintenanceRequests.map((request) => <article key={request.id} className="rounded-3xl bg-emerald-50 p-4"><div className="flex items-center justify-between gap-2"><p className="flex items-center gap-2 font-black"><RefreshCw size={18} />Wartungsanfrage</p><Badge>{request.status}</Badge></div><p className="mt-2 text-sm">Zeitraum: {request.preferredPeriod || "offen"}</p>{request.message && <p className="mt-2 text-sm">{request.message}</p>}</article>)}
    {portal.approvals.map((approval) => <article key={approval.id} className="rounded-3xl bg-violet-50 p-4"><p className="flex items-center gap-2 font-black"><ShieldCheck size={18} />{approval.approvalType}</p><p className="mt-1 text-xs font-bold text-violet-900">Interne Kenntnisnahme · {approval.createdAt}</p></article>)}</div>
  </Card></div>;
}
