import React from "react";
import { BookOpen, ClipboardCheck, FileText, MessageSquareText, Play, Target } from "lucide-react";
import { Badge } from "../CheckItem";

export default function LearningOverview({ assignments = [], comments = [], learner, onNavigate, recommendations = [], reports = [], summary, week }) {
  const next = recommendations[0];
  const openAssignment = assignments.find((item) => item.status !== "erledigt");
  const openComment = comments.find((item) => item.status !== "erledigt");
  return <div className="space-y-5">
    <section className="rounded-3xl bg-slate-950 p-5 text-white"><div className="flex flex-wrap items-center justify-between gap-3"><div><Badge>Ausbildungsjahr {learner?.trainingYear || 1}</Badge><h2 className="mt-3 text-2xl font-black">Was solltest du als Nächstes lernen?</h2></div><div className="text-right"><p className="text-3xl font-black">{summary.overall}%</p><p className="text-xs font-bold text-white/60">Gesamtfortschritt</p></div></div>{next ? <div className="mt-5 rounded-2xl bg-white/10 p-4"><p className="text-xs font-black uppercase text-white/50">Nächster Schritt · {next.reason}</p><h3 className="mt-2 text-lg font-black">{next.module.title}</h3><button type="button" onClick={() => onNavigate("modules", next.module.id)} className="mt-3 flex min-h-11 items-center gap-2 rounded-xl bg-white px-4 text-xs font-black text-slate-950"><Play size={16} />Weiterlernen</button></div> : <p className="mt-5 rounded-2xl bg-emerald-400/15 p-4 text-sm font-bold text-emerald-100">Der aktuelle Lernpfad ist vollständig. Praxis und Wiederholung bleiben trotzdem sinnvoll.</p>}</section>

    <section><h3 className="font-black">Heute</h3><div className="mt-3 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><button type="button" onClick={() => onNavigate("modules", next?.module.id)} className="rounded-3xl bg-sky-50 p-4 text-left"><BookOpen size={20} /><span className="mt-3 block text-xs font-black uppercase text-sky-700">Lernmodul</span><span className="mt-1 block font-black">{next?.module.title || "Modul auswählen"}</span></button><button type="button" onClick={() => onNavigate("practice")} className="rounded-3xl bg-emerald-50 p-4 text-left"><ClipboardCheck size={20} /><span className="mt-3 block text-xs font-black uppercase text-emerald-700">Praxisaufgabe</span><span className="mt-1 block font-black">{openAssignment?.title || "Praxisfall dokumentieren"}</span></button><button type="button" onClick={() => onNavigate("reports")} className="rounded-3xl bg-amber-50 p-4 text-left"><FileText size={20} /><span className="mt-3 block text-xs font-black uppercase text-amber-700">Berichtsheft</span><span className="mt-1 block font-black">{reports.filter((report) => report.status !== "Freigegeben").length} Eintrag/Einträge offen</span></button><button type="button" onClick={() => onNavigate("quiz")} className="rounded-3xl bg-violet-50 p-4 text-left"><Target size={20} /><span className="mt-3 block text-xs font-black uppercase text-violet-700">Quiz-Wiederholung</span><span className="mt-1 block font-black">{summary.quizAnswers ? "Schwache Themen üben" : "Erstes Tagesquiz"}</span></button></div></section>

    <section className="grid gap-4 lg:grid-cols-[1.2fr_0.8fr]"><div className="rounded-3xl bg-slate-50 p-5"><h3 className="font-black">Diese Woche</h3><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><div><p className="text-2xl font-black">{week.completedModules}</p><p className="text-xs font-bold text-slate-500">Module</p></div><div><p className="text-2xl font-black">{week.practiceCases}</p><p className="text-xs font-bold text-slate-500">Praxisfälle</p></div><div><p className="text-2xl font-black">{week.openReports}</p><p className="text-xs font-bold text-slate-500">Berichte offen</p></div><div><p className="text-2xl font-black">{week.quizAnswers}</p><p className="text-xs font-bold text-slate-500">Quizantworten</p></div></div><p className="mt-4 text-xs font-bold text-slate-500">Dezent: {week.learningDays} Lerntag(e) in den letzten sieben Tagen.</p></div><div className="rounded-3xl bg-slate-50 p-5"><div className="flex items-center gap-2"><MessageSquareText size={18} /><h3 className="font-black">Kommentare & Ziel</h3></div><p className="mt-3 text-sm font-bold">{openComment?.text || openAssignment?.comment || "Noch kein offener Meister-Kommentar."}</p>{(openComment || openAssignment) && <button type="button" onClick={() => onNavigate("progress")} className="mt-3 min-h-11 rounded-xl bg-white px-4 text-xs font-black">Öffnen</button>}</div></section>
  </div>;
}
