import React from "react";
import { FileText, MessageSquareText } from "lucide-react";
import { Badge } from "../CheckItem";

export default function LearningReports({ canReview, learnerId, onOpenReportBook, onReview, reports = [] }) {
  const visible = reports.filter((report) => !learnerId || report.createdBy === learnerId || !report.createdBy);
  return <div className="space-y-4"><div className="flex flex-col gap-3 rounded-3xl bg-slate-50 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-black">Berichtsheft-Verknüpfung</h3><p className="mt-1 text-xs font-semibold text-slate-500">Entwürfe aus Auftrag, Praxisfall oder Lernmodul müssen vom Azubi geprüft und selbst gespeichert werden.</p></div><button type="button" onClick={() => onOpenReportBook("")} className="min-h-12 rounded-2xl bg-slate-950 px-4 text-sm font-black text-white">Berichtsheft öffnen</button></div><div className="grid gap-4 lg:grid-cols-2">{visible.map((report) => <ReportCard key={report.id} canReview={canReview} onReview={onReview} report={report}/>) }{!visible.length && <div className="rounded-3xl bg-slate-50 p-6 text-center"><FileText className="mx-auto text-slate-300"/><p className="mt-3 font-black">Noch kein Bericht gespeichert.</p><button type="button" onClick={() => onOpenReportBook("")} className="mt-3 min-h-11 rounded-xl bg-white px-4 text-xs font-black">Ersten Bericht schreiben</button></div>}</div></div>;
}

function ReportCard({canReview,onReview,report}) {
  const [comment,setComment] = React.useState(report.masterComment || "");
  return <article className="rounded-3xl bg-slate-50 p-5"><div className="flex flex-wrap gap-2"><Badge>{report.status}</Badge><Badge>{report.mode}</Badge><Badge>{report.orderId || "ohne Auftrag"}</Badge></div><h4 className="mt-3 font-black">{report.userName || "Lernender"} · {report.createdAt}</h4><p className="mt-3 line-clamp-5 whitespace-pre-line text-sm leading-6 text-slate-600">{report.text}</p>{report.masterComment && <div className="mt-3 rounded-2xl bg-white p-3 text-sm"><MessageSquareText size={16} className="mr-2 inline"/><strong>Meister:</strong> {report.masterComment}</div>}{canReview && <div className="mt-4"><textarea value={comment} onChange={(event)=>setComment(event.target.value)} placeholder="Sachlicher Meister-Kommentar" className="min-h-24 w-full rounded-2xl border border-slate-200 bg-white p-3 text-sm"/><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" onClick={()=>onReview(report.id,"Änderung erforderlich",comment)} className="min-h-11 rounded-xl bg-amber-100 px-3 text-xs font-black text-amber-900">Änderung anfordern</button><button type="button" onClick={()=>onReview(report.id,"Freigegeben",comment)} className="min-h-11 rounded-xl bg-emerald-100 px-3 text-xs font-black text-emerald-900">Freigeben</button></div></div>}</article>;
}
