import React, { useEffect, useMemo, useState } from "react";
import { BookOpen, BriefcaseBusiness, FileText, Plus, Save } from "lucide-react";
import { Badge } from "../CheckItem";
import { buildPracticeReportDraft, suggestModulesForContext } from "../../lib/learningSystem";

const emptyDraft = (learnerId) => ({ learnerId, title:"", task:"", initialSituation:"", approach:"", tools:[], learned:"", difficult:"", openQuestion:"", moduleIds:[], status:"Entwurf" });

export default function LearningPracticeCases({ learnerId, modules, onCreateFromOrder, onPrepareReport, onSave, orders = [], practiceCases = [], readOnly }) {
  const [draft, setDraft] = useState(() => emptyDraft(learnerId));
  const [toolText, setToolText] = useState("");
  useEffect(() => { setDraft(emptyDraft(learnerId)); setToolText(""); }, [learnerId]);
  const learnerCases = practiceCases.filter((item) => item.learnerId === learnerId);
  const suggestions = useMemo(() => suggestModulesForContext({productName:draft.title,product:draft.initialSituation,orderType:draft.task},modules),[draft.initialSituation,draft.task,draft.title,modules]);
  const save = () => { if (!draft.title.trim() || !draft.task.trim()) return; onSave({...draft,id:draft.id || `PRAXIS-${Date.now()}`,sourceType:draft.sourceType || "manual",tools:toolText.split(",").map((item)=>item.trim()).filter(Boolean),moduleIds:draft.moduleIds.length?draft.moduleIds:suggestions.slice(0,4).map((module)=>module.id),createdAt:draft.createdAt || new Date().toISOString(),updatedAt:new Date().toISOString()}); setDraft(emptyDraft(learnerId)); setToolText(""); };
  return <div className="space-y-5"><section className="rounded-3xl bg-slate-50 p-5"><div className="flex items-center gap-2"><BriefcaseBusiness size={19}/><h3 className="font-black">Zugewiesene Aufträge als Lernfall</h3></div><p className="mt-1 text-xs font-semibold text-slate-500">Es werden nur technische Angaben übernommen – keine Kundenadresse und kein Kundenname im Lerntext.</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{orders.map((order) => <article key={order.id} className="rounded-2xl bg-white p-4"><div className="flex flex-wrap gap-2"><Badge>{order.id}</Badge><Badge>{order.orderType || "Auftrag"}</Badge></div><h4 className="mt-2 font-black">{order.productName || order.product}</h4><p className="mt-1 text-xs font-semibold text-slate-500">{[order.substrate,order.drive,order.manufacturer].filter(Boolean).join(" · ")}</p><button type="button" disabled={readOnly} onClick={() => onCreateFromOrder(order)} className="mt-3 min-h-11 w-full rounded-xl bg-slate-950 px-3 text-xs font-black text-white disabled:opacity-40">Als Lernfall verwenden</button></article>)}{!orders.length && <p className="rounded-2xl bg-white p-4 text-sm font-bold text-slate-500">Keine zugewiesenen Aufträge verfügbar.</p>}</div></section>
    {!readOnly && <details className="rounded-3xl bg-slate-50 p-5"><summary className="cursor-pointer font-black"><Plus size={18} className="mr-2 inline"/>Praxisfall manuell hinzufügen</summary><div className="mt-4 grid gap-3 md:grid-cols-2">{[["Titel","title"],["Aufgabe","task"],["Ausgangslage","initialSituation"],["Mein Vorgehen","approach"],["Was habe ich gelernt?","learned"],["Was war schwierig?","difficult"],["Offene Frage","openQuestion"]].map(([label,key]) => <label key={key} className="text-sm font-black">{label}<textarea value={draft[key]} onChange={(event)=>setDraft({...draft,[key]:event.target.value})} className="mt-2 min-h-24 w-full rounded-2xl border border-slate-200 bg-white p-3 text-sm font-medium" /></label>)}<label className="text-sm font-black">Verwendetes Werkzeug, durch Komma getrennt<input value={toolText} onChange={(event)=>setToolText(event.target.value)} className="mt-2 min-h-12 w-full rounded-2xl border border-slate-200 bg-white px-3 text-sm" /></label><label className="text-sm font-black">Status<select value={draft.status} onChange={(event)=>setDraft({...draft,status:event.target.value})} className="mt-2 min-h-12 w-full rounded-2xl border border-slate-200 bg-white px-3"><option>Entwurf</option><option>Dokumentiert</option><option>Mit Meister besprochen</option></select></label></div><div className="mt-4"><p className="text-xs font-black uppercase text-slate-500">Vorgeschlagene Lernmodule</p><div className="mt-2 flex flex-wrap gap-2">{suggestions.map((module)=><button key={module.id} type="button" onClick={()=>setDraft({...draft,moduleIds:draft.moduleIds.includes(module.id)?draft.moduleIds.filter((id)=>id!==module.id):[...draft.moduleIds,module.id]})} className={`rounded-full px-3 py-2 text-xs font-black ${draft.moduleIds.includes(module.id)?"bg-slate-950 text-white":"bg-white"}`}>{module.title}</button>)}</div></div><button type="button" onClick={save} className="mt-4 flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-slate-950 px-4 text-sm font-black text-white"><Save size={17}/>Praxisfall speichern</button></details>}
    <section><h3 className="font-black">Gespeicherte Praxisfälle</h3><div className="mt-3 grid gap-4 lg:grid-cols-2">{learnerCases.map((item)=><article key={item.id} className="rounded-3xl bg-slate-50 p-5"><div className="flex flex-wrap gap-2"><Badge>{item.status}</Badge><Badge>{item.sourceType === "diagnosis" ? "Diagnose" : item.sourceType === "order" ? "Auftrag" : "Eigener Fall"}</Badge></div><h4 className="mt-3 text-lg font-black">{item.title}</h4><p className="mt-2 text-sm leading-6 text-slate-600">{item.initialSituation}</p><details className="mt-3 rounded-2xl bg-white p-3"><summary className="cursor-pointer text-xs font-black uppercase text-slate-500">Dokumentation</summary><div className="mt-3 space-y-2 text-sm leading-6"><p><strong>Vorgehen:</strong> {item.approach || "noch offen"}</p><p><strong>Gelernt:</strong> {item.learned || "noch offen"}</p><p><strong>Schwierig:</strong> {item.difficult || "noch offen"}</p><p><strong>Frage:</strong> {item.openQuestion || "keine"}</p></div></details><div className="mt-3 flex flex-wrap gap-2">{(item.moduleIds||[]).map((id)=><Badge key={id}>{modules.find((module)=>module.id===id)?.title || id}</Badge>)}</div><button type="button" onClick={()=>onPrepareReport(buildPracticeReportDraft(item,modules),item)} className="mt-4 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-white text-xs font-black"><FileText size={16}/>Berichtsheft-Entwurf vorbereiten</button></article>)}{!learnerCases.length && <div className="rounded-3xl bg-slate-50 p-6 text-center"><BookOpen className="mx-auto text-slate-300"/><p className="mt-3 font-black">Noch kein Praxisfall gespeichert.</p><p className="mt-1 text-sm text-slate-500">Nutze einen Auftrag oder erstelle den ersten Fall manuell.</p></div>}</div></section></div>;
}
