import React, { useMemo, useState } from "react";
import { CalendarOff, Plus, Trash2 } from "lucide-react";
import { ABSENCE_TYPES } from "../../data/planning";

const initialForm = { personId: "", startDate: "", endDate: "", type: "Urlaub", note: "" };

export default function AbsenceManager({ absences, canManage, onCreate, onDelete, people }) {
  const [form, setForm] = useState(initialForm);
  const sorted = useMemo(() => [...absences].sort((left, right) => `${left.startDate}:${left.personId}`.localeCompare(`${right.startDate}:${right.personId}`)), [absences]);
  const submit = () => {
    if (!form.personId || !form.startDate) return;
    onCreate({ ...form, endDate: form.endDate || form.startDate });
    setForm(initialForm);
  };
  return <div className="grid gap-5 lg:grid-cols-[0.8fr_1.2fr]">
    <section className="rounded-[2rem] bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><span className="rounded-2xl bg-slate-950 p-3 text-white"><CalendarOff size={20} /></span><div><h2 className="text-xl font-black">Abwesenheit</h2><p className="text-sm text-slate-600">Urlaub, Krankheit, Schule oder Lehrgang einfach vormerken.</p></div></div>{canManage ? <div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold sm:col-span-2">Person<select value={form.personId} onChange={(event) => setForm({ ...form, personId: event.target.value })} className="mt-1 min-h-11 w-full rounded-xl border border-slate-200 px-3"><option value="">Person auswählen</option>{people.filter((person) => person.role !== "kunde" && person.status === "aktiv").map((person) => <option key={person.id} value={person.id}>{person.name} · {person.role}</option>)}</select></label><label className="text-sm font-bold">Von<input type="date" value={form.startDate} onChange={(event) => setForm({ ...form, startDate: event.target.value })} className="mt-1 min-h-11 w-full rounded-xl border border-slate-200 px-3" /></label><label className="text-sm font-bold">Bis<input type="date" value={form.endDate} onChange={(event) => setForm({ ...form, endDate: event.target.value })} className="mt-1 min-h-11 w-full rounded-xl border border-slate-200 px-3" /></label><label className="text-sm font-bold sm:col-span-2">Typ<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })} className="mt-1 min-h-11 w-full rounded-xl border border-slate-200 px-3">{ABSENCE_TYPES.map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-sm font-bold sm:col-span-2">Notiz<textarea value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })} className="mt-1 h-20 w-full resize-none rounded-xl border border-slate-200 p-3" /></label><button type="button" onClick={submit} className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 text-sm font-black text-white sm:col-span-2"><Plus size={18} />Abwesenheit speichern</button></div> : <p className="mt-5 rounded-2xl bg-slate-50 p-4 text-sm font-bold text-slate-500">Abwesenheiten sind für diese Rolle nur lesbar.</p>}</section>
    <section className="rounded-[2rem] bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Erfasste Abwesenheiten</h2><div className="mt-4 space-y-2">{sorted.map((absence) => { const person = people.find((item) => item.id === absence.personId); return <div key={absence.id} className="flex items-start justify-between gap-3 rounded-2xl bg-slate-50 p-4"><div><strong>{person?.name || "Unbekannte Person"}</strong><p className="mt-1 text-xs font-bold text-slate-500">{absence.startDate} bis {absence.endDate} · {absence.type}</p>{absence.note && <p className="mt-2 text-sm text-slate-600">{absence.note}</p>}</div>{canManage && <button type="button" onClick={() => onDelete(absence.id)} className="rounded-xl bg-rose-100 p-3 text-rose-800" aria-label="Abwesenheit löschen"><Trash2 size={16} /></button>}</div>; })}{!sorted.length && <p className="rounded-2xl bg-slate-50 p-5 text-sm font-bold text-slate-500">Noch keine Abwesenheiten erfasst.</p>}</div></section>
  </div>;
}
