import React from "react";
import { UsersRound } from "lucide-react";
import { Badge } from "../CheckItem";
import { getTeamLoad, isPersonAbsent } from "../../lib/planning";

export default function TeamSchedule({ absences, orders, people, selectedDate }) {
  const internal = people.filter((person) => person.role !== "kunde" && person.status === "aktiv");
  const crews = [...new Set(internal.map((person) => person.team || "Flexibles Team"))];
  return <div className="grid gap-4 xl:grid-cols-2">{crews.map((crew) => { const members = internal.filter((person) => (person.team || "Flexibles Team") === crew); const crewOrders = orders.filter((order) => order.date === selectedDate && (order.crew === crew || (order.assignedMemberIds || []).some((id) => members.some((person) => person.id === id)))); return <section key={crew} className="rounded-[2rem] bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="rounded-2xl bg-slate-950 p-3 text-white"><UsersRound size={20} /></span><div><h2 className="font-black">{crew}</h2><p className="text-xs font-bold text-slate-500">{crewOrders.length} Auftrag{crewOrders.length === 1 ? "" : "e"} am gewählten Tag</p></div></div><Badge>{crewOrders.length >= 3 ? "stark belegt" : crewOrders.length ? "belegt" : "frei"}</Badge></div><div className="mt-4 space-y-2">{members.map((person) => { const load = getTeamLoad(orders, person.id, selectedDate); const absence = isPersonAbsent(person.id, selectedDate, absences); return <div key={person.id} className={`flex items-center justify-between rounded-2xl p-3 text-sm ${absence ? "bg-amber-50" : "bg-slate-50"}`}><span><strong>{person.name}</strong><span className="block text-xs font-bold text-slate-500">{person.role}{absence ? ` · ${absence.type}` : ""}</span></span><Badge>{absence ? "abwesend" : load.label}</Badge></div>; })}</div><div className="mt-4 space-y-2">{crewOrders.map((order) => <div key={order.id} className="rounded-2xl bg-slate-950 p-3 text-sm text-white"><strong>{order.time || "Zeit offen"} · {order.id}</strong><p className="mt-1 text-xs text-white/65">{order.customer}</p></div>)}{!crewOrders.length && <p className="rounded-2xl bg-slate-50 p-3 text-xs font-bold text-slate-400">Keine Baustelle eingeplant.</p>}</div></section>; })}</div>;
}
